import mongoose, { Document, Schema } from 'mongoose';

/**
 * Resume Model - Simplified Schema
 * 
 * Core fields:
 * - resume_id (auto-generated _id)
 * - group_id (reference to ResumeGroup)
 * - filename, original_name (file info)
 * - original_name (extracted from filename)
 * - raw_text (extracted text from PDF)
 * - status fields (extraction_status, parsing_status, embedding_status)
 * - parsed_content (ALL AI parser output stored as-is)
 * - resume_embedding (6-section embeddings for semantic scoring)
 * - timestamps
 */

export interface IResume extends Document {
  // File information
  filename: string;
  original_name: string;
  group_id?: mongoose.Types.ObjectId;
  
  // Extracted text
  raw_text?: string;
  
  // Processing status
  extraction_status: 'pending' | 'success' | 'failed';
  parsing_status: 'pending' | 'success' | 'failed';
  embedding_status: 'pending' | 'success' | 'failed';
  
  // AI Parser output - stored as-is (matches c_ai_parser.py output exactly)
  parsed_content?: Record<string, any>;
  
  // Resume embeddings for semantic scoring (6 sections from d_embedding_generator.py)
  // Each section contains array of sentence embeddings (2D: [[emb1], [emb2], ...])
  resume_embedding?: {
    model?: string;
    dimension?: number;
    profile?: number[][];
    skills?: number[][];
    projects?: number[][];
    responsibilities?: number[][];
    education?: number[][];
    overall?: number[][];
  };
  
  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

const resumeSchema = new Schema<IResume>({
  // File information
  filename: {
    type: String,
    required: true,
    index: true
  },
  original_name: {
    type: String,
    required: true
  },
  group_id: {
    type: Schema.Types.ObjectId,
    ref: 'ResumeGroup',
    index: true
  },
  
  // Extracted text from PDF
  raw_text: {
    type: String
  },
  
  // Processing status fields
  extraction_status: {
    type: String,
    enum: ['pending', 'success', 'failed'],
    default: 'pending',
    index: true
  },
  parsing_status: {
    type: String,
    enum: ['pending', 'success', 'failed'],
    default: 'pending',
    index: true
  },
  embedding_status: {
    type: String,
    enum: ['pending', 'success', 'failed'],
    default: 'pending',
    index: true
  },
  
  // AI Parser output - stored as flexible object (matches c_ai_parser.py output)
  // Contains: name, contact_info, experience, education, skills, canonical_skills,
  // inferred_skills, skill_proficiency, projects, certifications, languages, etc.
  parsed_content: {
    type: Schema.Types.Mixed,
    default: {}
  },
  
  // Resume embeddings (6 sections for semantic scoring)
  // Each section is 2D array: [[emb1], [emb2], ...] for multiple sentences
  // Generated by d_embedding_generator.py
  resume_embedding: {
    model: {
      type: String,
      default: 'text-embedding-3-small'
    },
    dimension: {
      type: Number,
      default: 1536
    },
    profile: {
      type: Schema.Types.Mixed,
      default: []
    },
    skills: {
      type: Schema.Types.Mixed,
      default: []
    },
    projects: {
      type: Schema.Types.Mixed,
      default: []
    },
    responsibilities: {
      type: Schema.Types.Mixed,
      default: []
    },
    education: {
      type: Schema.Types.Mixed,
      default: []
    },
    overall: {
      type: Schema.Types.Mixed,
      default: []
    }
  }
}, {
  timestamps: true
});

// Indexes for efficient queries
resumeSchema.index({ group_id: 1, parsing_status: 1 });
resumeSchema.index({ 'parsed_content.name': 1 });
resumeSchema.index({ 'parsed_content.contact_info.email': 1 });

// Virtual for candidate name (extracted from parsed_content)
resumeSchema.virtual('candidate_name').get(function() {
  return this.parsed_content?.name || this.original_name || 'Unknown';
});

// Virtual for candidate email
resumeSchema.virtual('candidate_email').get(function() {
  return this.parsed_content?.contact_info?.email || '';
});

// Ensure virtuals are included in JSON output
resumeSchema.set('toJSON', { virtuals: true });
resumeSchema.set('toObject', { virtuals: true });

export default mongoose.model<IResume>('Resume', resumeSchema);